var iceCream = "Chocolate";
var favColor = "Black";
var favDish = "Singaporian Rice";
var equation = null;
var isDay = false;
var isStudent = true;
var result = undefined;
var x = 87;
var y = 15;
var xy = 102;
console.log("Is iceCream == Chocolate? i predict True.");
console.log(iceCream = "Chocolate");
console.log("Is favColor == Black? i predict True.");
console.log(favColor = "Black");
console.log("Is favDish == Singaporian Rice? i predict True.");
console.log(favDish = "Singaporian Rice");
console.log("Is equation ==  2x+8y(3+2x)? i predict False.");
console.log(equation = null);
console.log("Is isDay == false? i predict True.");
console.log(isDay == false);
console.log("Is isStudent == false? I predict False");
console.log(isStudent == true);
console.log("Is result = undefined? I predict True");
console.log(result = undefined);
console.log("Is let x = 87? i predict True.");
console.log(x = 87);
console.log("Is  y = 5? i predict False.");
console.log(y = 15);
console.log("Is xy>=x? i predict True.");
console.log(xy >= x);
